// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: yyets/v1/adsense.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAdsenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdsenseRequest) Reset() {
	*x = CreateAdsenseRequest{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdsenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdsenseRequest) ProtoMessage() {}

func (x *CreateAdsenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdsenseRequest.ProtoReflect.Descriptor instead.
func (*CreateAdsenseRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{0}
}

type CreateAdsenseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdsenseReply) Reset() {
	*x = CreateAdsenseReply{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdsenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdsenseReply) ProtoMessage() {}

func (x *CreateAdsenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdsenseReply.ProtoReflect.Descriptor instead.
func (*CreateAdsenseReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{1}
}

type UpdateAdsenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdsenseRequest) Reset() {
	*x = UpdateAdsenseRequest{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdsenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdsenseRequest) ProtoMessage() {}

func (x *UpdateAdsenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdsenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdsenseRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{2}
}

type UpdateAdsenseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdsenseReply) Reset() {
	*x = UpdateAdsenseReply{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdsenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdsenseReply) ProtoMessage() {}

func (x *UpdateAdsenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdsenseReply.ProtoReflect.Descriptor instead.
func (*UpdateAdsenseReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{3}
}

type DeleteAdsenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdsenseRequest) Reset() {
	*x = DeleteAdsenseRequest{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdsenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdsenseRequest) ProtoMessage() {}

func (x *DeleteAdsenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdsenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdsenseRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{4}
}

type DeleteAdsenseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdsenseReply) Reset() {
	*x = DeleteAdsenseReply{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdsenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdsenseReply) ProtoMessage() {}

func (x *DeleteAdsenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdsenseReply.ProtoReflect.Descriptor instead.
func (*DeleteAdsenseReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{5}
}

type GetAdsenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdsenseRequest) Reset() {
	*x = GetAdsenseRequest{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdsenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdsenseRequest) ProtoMessage() {}

func (x *GetAdsenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdsenseRequest.ProtoReflect.Descriptor instead.
func (*GetAdsenseRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{6}
}

type GetAdsenseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdsenseReply) Reset() {
	*x = GetAdsenseReply{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdsenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdsenseReply) ProtoMessage() {}

func (x *GetAdsenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdsenseReply.ProtoReflect.Descriptor instead.
func (*GetAdsenseReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{7}
}

type ListAdsenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsenseRequest) Reset() {
	*x = ListAdsenseRequest{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsenseRequest) ProtoMessage() {}

func (x *ListAdsenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsenseRequest.ProtoReflect.Descriptor instead.
func (*ListAdsenseRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{8}
}

type ListAdsenseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsenseReply) Reset() {
	*x = ListAdsenseReply{}
	mi := &file_yyets_v1_adsense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsenseReply) ProtoMessage() {}

func (x *ListAdsenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_adsense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsenseReply.ProtoReflect.Descriptor instead.
func (*ListAdsenseReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_adsense_proto_rawDescGZIP(), []int{9}
}

func (x *ListAdsenseReply) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_yyets_v1_adsense_proto protoreflect.FileDescriptor

const file_yyets_v1_adsense_proto_rawDesc = "" +
	"\n" +
	"\x16yyets/v1/adsense.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\"\x16\n" +
	"\x14CreateAdsenseRequest\"\x14\n" +
	"\x12CreateAdsenseReply\"\x16\n" +
	"\x14UpdateAdsenseRequest\"\x14\n" +
	"\x12UpdateAdsenseReply\"\x16\n" +
	"\x14DeleteAdsenseRequest\"\x14\n" +
	"\x12DeleteAdsenseReply\"\x13\n" +
	"\x11GetAdsenseRequest\"\x11\n" +
	"\x0fGetAdsenseReply\"\x14\n" +
	"\x12ListAdsenseRequest\"&\n" +
	"\x10ListAdsenseReply\x12\x12\n" +
	"\x04data\x18\x01 \x03(\tR\x04data2\xc3\x03\n" +
	"\aAdsense\x12U\n" +
	"\rCreateAdsense\x12\".api.yyets.v1.CreateAdsenseRequest\x1a .api.yyets.v1.CreateAdsenseReply\x12U\n" +
	"\rUpdateAdsense\x12\".api.yyets.v1.UpdateAdsenseRequest\x1a .api.yyets.v1.UpdateAdsenseReply\x12U\n" +
	"\rDeleteAdsense\x12\".api.yyets.v1.DeleteAdsenseRequest\x1a .api.yyets.v1.DeleteAdsenseReply\x12L\n" +
	"\n" +
	"GetAdsense\x12\x1f.api.yyets.v1.GetAdsenseRequest\x1a\x1d.api.yyets.v1.GetAdsenseReply\x12e\n" +
	"\vListAdsense\x12 .api.yyets.v1.ListAdsenseRequest\x1a\x1e.api.yyets.v1.ListAdsenseReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/adsenseB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_yyets_v1_adsense_proto_rawDescOnce sync.Once
	file_yyets_v1_adsense_proto_rawDescData []byte
)

func file_yyets_v1_adsense_proto_rawDescGZIP() []byte {
	file_yyets_v1_adsense_proto_rawDescOnce.Do(func() {
		file_yyets_v1_adsense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yyets_v1_adsense_proto_rawDesc), len(file_yyets_v1_adsense_proto_rawDesc)))
	})
	return file_yyets_v1_adsense_proto_rawDescData
}

var file_yyets_v1_adsense_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_yyets_v1_adsense_proto_goTypes = []any{
	(*CreateAdsenseRequest)(nil), // 0: api.yyets.v1.CreateAdsenseRequest
	(*CreateAdsenseReply)(nil),   // 1: api.yyets.v1.CreateAdsenseReply
	(*UpdateAdsenseRequest)(nil), // 2: api.yyets.v1.UpdateAdsenseRequest
	(*UpdateAdsenseReply)(nil),   // 3: api.yyets.v1.UpdateAdsenseReply
	(*DeleteAdsenseRequest)(nil), // 4: api.yyets.v1.DeleteAdsenseRequest
	(*DeleteAdsenseReply)(nil),   // 5: api.yyets.v1.DeleteAdsenseReply
	(*GetAdsenseRequest)(nil),    // 6: api.yyets.v1.GetAdsenseRequest
	(*GetAdsenseReply)(nil),      // 7: api.yyets.v1.GetAdsenseReply
	(*ListAdsenseRequest)(nil),   // 8: api.yyets.v1.ListAdsenseRequest
	(*ListAdsenseReply)(nil),     // 9: api.yyets.v1.ListAdsenseReply
}
var file_yyets_v1_adsense_proto_depIdxs = []int32{
	0, // 0: api.yyets.v1.Adsense.CreateAdsense:input_type -> api.yyets.v1.CreateAdsenseRequest
	2, // 1: api.yyets.v1.Adsense.UpdateAdsense:input_type -> api.yyets.v1.UpdateAdsenseRequest
	4, // 2: api.yyets.v1.Adsense.DeleteAdsense:input_type -> api.yyets.v1.DeleteAdsenseRequest
	6, // 3: api.yyets.v1.Adsense.GetAdsense:input_type -> api.yyets.v1.GetAdsenseRequest
	8, // 4: api.yyets.v1.Adsense.ListAdsense:input_type -> api.yyets.v1.ListAdsenseRequest
	1, // 5: api.yyets.v1.Adsense.CreateAdsense:output_type -> api.yyets.v1.CreateAdsenseReply
	3, // 6: api.yyets.v1.Adsense.UpdateAdsense:output_type -> api.yyets.v1.UpdateAdsenseReply
	5, // 7: api.yyets.v1.Adsense.DeleteAdsense:output_type -> api.yyets.v1.DeleteAdsenseReply
	7, // 8: api.yyets.v1.Adsense.GetAdsense:output_type -> api.yyets.v1.GetAdsenseReply
	9, // 9: api.yyets.v1.Adsense.ListAdsense:output_type -> api.yyets.v1.ListAdsenseReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yyets_v1_adsense_proto_init() }
func file_yyets_v1_adsense_proto_init() {
	if File_yyets_v1_adsense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yyets_v1_adsense_proto_rawDesc), len(file_yyets_v1_adsense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yyets_v1_adsense_proto_goTypes,
		DependencyIndexes: file_yyets_v1_adsense_proto_depIdxs,
		MessageInfos:      file_yyets_v1_adsense_proto_msgTypes,
	}.Build()
	File_yyets_v1_adsense_proto = out.File
	file_yyets_v1_adsense_proto_goTypes = nil
	file_yyets_v1_adsense_proto_depIdxs = nil
}
