// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: yyets/v1/announcement.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnouncementRequest) Reset() {
	*x = CreateAnnouncementRequest{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnouncementRequest) ProtoMessage() {}

func (x *CreateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*CreateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{0}
}

type CreateAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnouncementReply) Reset() {
	*x = CreateAnnouncementReply{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnouncementReply) ProtoMessage() {}

func (x *CreateAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnouncementReply.ProtoReflect.Descriptor instead.
func (*CreateAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{1}
}

type UpdateAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementRequest) Reset() {
	*x = UpdateAnnouncementRequest{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementRequest) ProtoMessage() {}

func (x *UpdateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{2}
}

type UpdateAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementReply) Reset() {
	*x = UpdateAnnouncementReply{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementReply) ProtoMessage() {}

func (x *UpdateAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementReply.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{3}
}

type DeleteAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnouncementRequest) Reset() {
	*x = DeleteAnnouncementRequest{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnouncementRequest) ProtoMessage() {}

func (x *DeleteAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{4}
}

type DeleteAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnouncementReply) Reset() {
	*x = DeleteAnnouncementReply{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnouncementReply) ProtoMessage() {}

func (x *DeleteAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnouncementReply.ProtoReflect.Descriptor instead.
func (*DeleteAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{5}
}

type GetAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementRequest) Reset() {
	*x = GetAnnouncementRequest{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementRequest) ProtoMessage() {}

func (x *GetAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{6}
}

type GetAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementReply) Reset() {
	*x = GetAnnouncementReply{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementReply) ProtoMessage() {}

func (x *GetAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementReply.ProtoReflect.Descriptor instead.
func (*GetAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{7}
}

type ListAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementRequest) Reset() {
	*x = ListAnnouncementRequest{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementRequest) ProtoMessage() {}

func (x *ListAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{8}
}

func (x *ListAnnouncementRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListAnnouncementRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListAnnouncementReply struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Count         int64                        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data          []*ListAnnouncementReplyItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementReply) Reset() {
	*x = ListAnnouncementReply{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementReply) ProtoMessage() {}

func (x *ListAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementReply.ProtoReflect.Descriptor instead.
func (*ListAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{9}
}

func (x *ListAnnouncementReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListAnnouncementReply) GetData() []*ListAnnouncementReplyItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListAnnouncementReplyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Browser       string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementReplyItem) Reset() {
	*x = ListAnnouncementReplyItem{}
	mi := &file_yyets_v1_announcement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementReplyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementReplyItem) ProtoMessage() {}

func (x *ListAnnouncementReplyItem) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_announcement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementReplyItem.ProtoReflect.Descriptor instead.
func (*ListAnnouncementReplyItem) Descriptor() ([]byte, []int) {
	return file_yyets_v1_announcement_proto_rawDescGZIP(), []int{10}
}

func (x *ListAnnouncementReplyItem) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *ListAnnouncementReplyItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ListAnnouncementReplyItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListAnnouncementReplyItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListAnnouncementReplyItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_yyets_v1_announcement_proto protoreflect.FileDescriptor

const file_yyets_v1_announcement_proto_rawDesc = "" +
	"\n" +
	"\x1byyets/v1/announcement.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x1b\n" +
	"\x19CreateAnnouncementRequest\"\x19\n" +
	"\x17CreateAnnouncementReply\"\x1b\n" +
	"\x19UpdateAnnouncementRequest\"\x19\n" +
	"\x17UpdateAnnouncementReply\"\x1b\n" +
	"\x19DeleteAnnouncementRequest\"\x19\n" +
	"\x17DeleteAnnouncementReply\"\x18\n" +
	"\x16GetAnnouncementRequest\"\x16\n" +
	"\x14GetAnnouncementReply\"U\n" +
	"\x17ListAnnouncementRequest\x12\x1d\n" +
	"\x04size\x18\x01 \x01(\x03B\t\xfaB\x06\"\x04\x18x \x00R\x04size\x12\x1b\n" +
	"\x04page\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x04page\"j\n" +
	"\x15ListAnnouncementReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12;\n" +
	"\x04data\x18\x02 \x03(\v2'.api.yyets.v1.ListAnnouncementReplyItemR\x04data\"\x8f\x01\n" +
	"\x19ListAnnouncementReplyItem\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername2\x98\x04\n" +
	"\fAnnouncement\x12d\n" +
	"\x12CreateAnnouncement\x12'.api.yyets.v1.CreateAnnouncementRequest\x1a%.api.yyets.v1.CreateAnnouncementReply\x12d\n" +
	"\x12UpdateAnnouncement\x12'.api.yyets.v1.UpdateAnnouncementRequest\x1a%.api.yyets.v1.UpdateAnnouncementReply\x12d\n" +
	"\x12DeleteAnnouncement\x12'.api.yyets.v1.DeleteAnnouncementRequest\x1a%.api.yyets.v1.DeleteAnnouncementReply\x12[\n" +
	"\x0fGetAnnouncement\x12$.api.yyets.v1.GetAnnouncementRequest\x1a\".api.yyets.v1.GetAnnouncementReply\x12y\n" +
	"\x10ListAnnouncement\x12%.api.yyets.v1.ListAnnouncementRequest\x1a#.api.yyets.v1.ListAnnouncementReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/announcementB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_yyets_v1_announcement_proto_rawDescOnce sync.Once
	file_yyets_v1_announcement_proto_rawDescData []byte
)

func file_yyets_v1_announcement_proto_rawDescGZIP() []byte {
	file_yyets_v1_announcement_proto_rawDescOnce.Do(func() {
		file_yyets_v1_announcement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yyets_v1_announcement_proto_rawDesc), len(file_yyets_v1_announcement_proto_rawDesc)))
	})
	return file_yyets_v1_announcement_proto_rawDescData
}

var file_yyets_v1_announcement_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_yyets_v1_announcement_proto_goTypes = []any{
	(*CreateAnnouncementRequest)(nil), // 0: api.yyets.v1.CreateAnnouncementRequest
	(*CreateAnnouncementReply)(nil),   // 1: api.yyets.v1.CreateAnnouncementReply
	(*UpdateAnnouncementRequest)(nil), // 2: api.yyets.v1.UpdateAnnouncementRequest
	(*UpdateAnnouncementReply)(nil),   // 3: api.yyets.v1.UpdateAnnouncementReply
	(*DeleteAnnouncementRequest)(nil), // 4: api.yyets.v1.DeleteAnnouncementRequest
	(*DeleteAnnouncementReply)(nil),   // 5: api.yyets.v1.DeleteAnnouncementReply
	(*GetAnnouncementRequest)(nil),    // 6: api.yyets.v1.GetAnnouncementRequest
	(*GetAnnouncementReply)(nil),      // 7: api.yyets.v1.GetAnnouncementReply
	(*ListAnnouncementRequest)(nil),   // 8: api.yyets.v1.ListAnnouncementRequest
	(*ListAnnouncementReply)(nil),     // 9: api.yyets.v1.ListAnnouncementReply
	(*ListAnnouncementReplyItem)(nil), // 10: api.yyets.v1.ListAnnouncementReplyItem
}
var file_yyets_v1_announcement_proto_depIdxs = []int32{
	10, // 0: api.yyets.v1.ListAnnouncementReply.data:type_name -> api.yyets.v1.ListAnnouncementReplyItem
	0,  // 1: api.yyets.v1.Announcement.CreateAnnouncement:input_type -> api.yyets.v1.CreateAnnouncementRequest
	2,  // 2: api.yyets.v1.Announcement.UpdateAnnouncement:input_type -> api.yyets.v1.UpdateAnnouncementRequest
	4,  // 3: api.yyets.v1.Announcement.DeleteAnnouncement:input_type -> api.yyets.v1.DeleteAnnouncementRequest
	6,  // 4: api.yyets.v1.Announcement.GetAnnouncement:input_type -> api.yyets.v1.GetAnnouncementRequest
	8,  // 5: api.yyets.v1.Announcement.ListAnnouncement:input_type -> api.yyets.v1.ListAnnouncementRequest
	1,  // 6: api.yyets.v1.Announcement.CreateAnnouncement:output_type -> api.yyets.v1.CreateAnnouncementReply
	3,  // 7: api.yyets.v1.Announcement.UpdateAnnouncement:output_type -> api.yyets.v1.UpdateAnnouncementReply
	5,  // 8: api.yyets.v1.Announcement.DeleteAnnouncement:output_type -> api.yyets.v1.DeleteAnnouncementReply
	7,  // 9: api.yyets.v1.Announcement.GetAnnouncement:output_type -> api.yyets.v1.GetAnnouncementReply
	9,  // 10: api.yyets.v1.Announcement.ListAnnouncement:output_type -> api.yyets.v1.ListAnnouncementReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_yyets_v1_announcement_proto_init() }
func file_yyets_v1_announcement_proto_init() {
	if File_yyets_v1_announcement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yyets_v1_announcement_proto_rawDesc), len(file_yyets_v1_announcement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yyets_v1_announcement_proto_goTypes,
		DependencyIndexes: file_yyets_v1_announcement_proto_depIdxs,
		MessageInfos:      file_yyets_v1_announcement_proto_msgTypes,
	}.Build()
	File_yyets_v1_announcement_proto = out.File
	file_yyets_v1_announcement_proto_goTypes = nil
	file_yyets_v1_announcement_proto_depIdxs = nil
}
