// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: yyets/v1/captcha.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCaptchaRequest) Reset() {
	*x = CreateCaptchaRequest{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaptchaRequest) ProtoMessage() {}

func (x *CreateCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaptchaRequest.ProtoReflect.Descriptor instead.
func (*CreateCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{0}
}

type CreateCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCaptchaReply) Reset() {
	*x = CreateCaptchaReply{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaptchaReply) ProtoMessage() {}

func (x *CreateCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaptchaReply.ProtoReflect.Descriptor instead.
func (*CreateCaptchaReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{1}
}

type UpdateCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCaptchaRequest) Reset() {
	*x = UpdateCaptchaRequest{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaptchaRequest) ProtoMessage() {}

func (x *UpdateCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaptchaRequest.ProtoReflect.Descriptor instead.
func (*UpdateCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{2}
}

type UpdateCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCaptchaReply) Reset() {
	*x = UpdateCaptchaReply{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaptchaReply) ProtoMessage() {}

func (x *UpdateCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaptchaReply.ProtoReflect.Descriptor instead.
func (*UpdateCaptchaReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{3}
}

type DeleteCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCaptchaRequest) Reset() {
	*x = DeleteCaptchaRequest{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCaptchaRequest) ProtoMessage() {}

func (x *DeleteCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCaptchaRequest.ProtoReflect.Descriptor instead.
func (*DeleteCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{4}
}

type DeleteCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCaptchaReply) Reset() {
	*x = DeleteCaptchaReply{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCaptchaReply) ProtoMessage() {}

func (x *DeleteCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCaptchaReply.ProtoReflect.Descriptor instead.
func (*DeleteCaptchaReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{5}
}

type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{6}
}

func (x *GetCaptchaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base64        string                 `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaReply) Reset() {
	*x = GetCaptchaReply{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaReply) ProtoMessage() {}

func (x *GetCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaReply.ProtoReflect.Descriptor instead.
func (*GetCaptchaReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{7}
}

func (x *GetCaptchaReply) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

type ListCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaptchaRequest) Reset() {
	*x = ListCaptchaRequest{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptchaRequest) ProtoMessage() {}

func (x *ListCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptchaRequest.ProtoReflect.Descriptor instead.
func (*ListCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{8}
}

type ListCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaptchaReply) Reset() {
	*x = ListCaptchaReply{}
	mi := &file_yyets_v1_captcha_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptchaReply) ProtoMessage() {}

func (x *ListCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_captcha_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptchaReply.ProtoReflect.Descriptor instead.
func (*ListCaptchaReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_captcha_proto_rawDescGZIP(), []int{9}
}

var File_yyets_v1_captcha_proto protoreflect.FileDescriptor

const file_yyets_v1_captcha_proto_rawDesc = "" +
	"\n" +
	"\x16yyets/v1/captcha.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\"\x16\n" +
	"\x14CreateCaptchaRequest\"\x14\n" +
	"\x12CreateCaptchaReply\"\x16\n" +
	"\x14UpdateCaptchaRequest\"\x14\n" +
	"\x12UpdateCaptchaReply\"\x16\n" +
	"\x14DeleteCaptchaRequest\"\x14\n" +
	"\x12DeleteCaptchaReply\"#\n" +
	"\x11GetCaptchaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x0fGetCaptchaReply\x12\x16\n" +
	"\x06base64\x18\x01 \x01(\tR\x06base64\"\x14\n" +
	"\x12ListCaptchaRequest\"\x12\n" +
	"\x10ListCaptchaReply2\xc3\x03\n" +
	"\aCaptcha\x12U\n" +
	"\rCreateCaptcha\x12\".api.yyets.v1.CreateCaptchaRequest\x1a .api.yyets.v1.CreateCaptchaReply\x12U\n" +
	"\rUpdateCaptcha\x12\".api.yyets.v1.UpdateCaptchaRequest\x1a .api.yyets.v1.UpdateCaptchaReply\x12U\n" +
	"\rDeleteCaptcha\x12\".api.yyets.v1.DeleteCaptchaRequest\x1a .api.yyets.v1.DeleteCaptchaReply\x12b\n" +
	"\n" +
	"GetCaptcha\x12\x1f.api.yyets.v1.GetCaptchaRequest\x1a\x1d.api.yyets.v1.GetCaptchaReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/captcha\x12O\n" +
	"\vListCaptcha\x12 .api.yyets.v1.ListCaptchaRequest\x1a\x1e.api.yyets.v1.ListCaptchaReplyB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_yyets_v1_captcha_proto_rawDescOnce sync.Once
	file_yyets_v1_captcha_proto_rawDescData []byte
)

func file_yyets_v1_captcha_proto_rawDescGZIP() []byte {
	file_yyets_v1_captcha_proto_rawDescOnce.Do(func() {
		file_yyets_v1_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yyets_v1_captcha_proto_rawDesc), len(file_yyets_v1_captcha_proto_rawDesc)))
	})
	return file_yyets_v1_captcha_proto_rawDescData
}

var file_yyets_v1_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_yyets_v1_captcha_proto_goTypes = []any{
	(*CreateCaptchaRequest)(nil), // 0: api.yyets.v1.CreateCaptchaRequest
	(*CreateCaptchaReply)(nil),   // 1: api.yyets.v1.CreateCaptchaReply
	(*UpdateCaptchaRequest)(nil), // 2: api.yyets.v1.UpdateCaptchaRequest
	(*UpdateCaptchaReply)(nil),   // 3: api.yyets.v1.UpdateCaptchaReply
	(*DeleteCaptchaRequest)(nil), // 4: api.yyets.v1.DeleteCaptchaRequest
	(*DeleteCaptchaReply)(nil),   // 5: api.yyets.v1.DeleteCaptchaReply
	(*GetCaptchaRequest)(nil),    // 6: api.yyets.v1.GetCaptchaRequest
	(*GetCaptchaReply)(nil),      // 7: api.yyets.v1.GetCaptchaReply
	(*ListCaptchaRequest)(nil),   // 8: api.yyets.v1.ListCaptchaRequest
	(*ListCaptchaReply)(nil),     // 9: api.yyets.v1.ListCaptchaReply
}
var file_yyets_v1_captcha_proto_depIdxs = []int32{
	0, // 0: api.yyets.v1.Captcha.CreateCaptcha:input_type -> api.yyets.v1.CreateCaptchaRequest
	2, // 1: api.yyets.v1.Captcha.UpdateCaptcha:input_type -> api.yyets.v1.UpdateCaptchaRequest
	4, // 2: api.yyets.v1.Captcha.DeleteCaptcha:input_type -> api.yyets.v1.DeleteCaptchaRequest
	6, // 3: api.yyets.v1.Captcha.GetCaptcha:input_type -> api.yyets.v1.GetCaptchaRequest
	8, // 4: api.yyets.v1.Captcha.ListCaptcha:input_type -> api.yyets.v1.ListCaptchaRequest
	1, // 5: api.yyets.v1.Captcha.CreateCaptcha:output_type -> api.yyets.v1.CreateCaptchaReply
	3, // 6: api.yyets.v1.Captcha.UpdateCaptcha:output_type -> api.yyets.v1.UpdateCaptchaReply
	5, // 7: api.yyets.v1.Captcha.DeleteCaptcha:output_type -> api.yyets.v1.DeleteCaptchaReply
	7, // 8: api.yyets.v1.Captcha.GetCaptcha:output_type -> api.yyets.v1.GetCaptchaReply
	9, // 9: api.yyets.v1.Captcha.ListCaptcha:output_type -> api.yyets.v1.ListCaptchaReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yyets_v1_captcha_proto_init() }
func file_yyets_v1_captcha_proto_init() {
	if File_yyets_v1_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yyets_v1_captcha_proto_rawDesc), len(file_yyets_v1_captcha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yyets_v1_captcha_proto_goTypes,
		DependencyIndexes: file_yyets_v1_captcha_proto_depIdxs,
		MessageInfos:      file_yyets_v1_captcha_proto_msgTypes,
	}.Build()
	File_yyets_v1_captcha_proto = out.File
	file_yyets_v1_captcha_proto_goTypes = nil
	file_yyets_v1_captcha_proto_depIdxs = nil
}
