// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/yyets/v1/comment.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Captcha       string                 `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CommentId     string                 `protobuf:"bytes,5,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommentRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *CreateCommentRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *CreateCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type CreateCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int64                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply) Reset() {
	*x = CreateCommentReply{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply) ProtoMessage() {}

func (x *CreateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply.ProtoReflect.Descriptor instead.
func (*CreateCommentReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCommentReply) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{2}
}

type UpdateCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentReply) Reset() {
	*x = UpdateCommentReply{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentReply) ProtoMessage() {}

func (x *UpdateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentReply.ProtoReflect.Descriptor instead.
func (*UpdateCommentReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{3}
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{4}
}

type DeleteCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply) Reset() {
	*x = DeleteCommentReply{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply) ProtoMessage() {}

func (x *DeleteCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{5}
}

type GetCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{6}
}

type GetCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReply) Reset() {
	*x = GetCommentReply{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReply) ProtoMessage() {}

func (x *GetCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReply.ProtoReflect.Descriptor instead.
func (*GetCommentReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{7}
}

type ListCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentRequest) Reset() {
	*x = ListCommentRequest{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentRequest) ProtoMessage() {}

func (x *ListCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentRequest.ProtoReflect.Descriptor instead.
func (*ListCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListCommentRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *ListCommentRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListCommentRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data          []*CommentItem         `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	ResourceId    int64                  `protobuf:"varint,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentReply) Reset() {
	*x = ListCommentReply{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentReply) ProtoMessage() {}

func (x *ListCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentReply.ProtoReflect.Descriptor instead.
func (*ListCommentReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListCommentReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListCommentReply) GetData() []*CommentItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListCommentReply) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type ListLatestCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestCommentRequest) Reset() {
	*x = ListLatestCommentRequest{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestCommentRequest) ProtoMessage() {}

func (x *ListLatestCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestCommentRequest.ProtoReflect.Descriptor instead.
func (*ListLatestCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *ListLatestCommentRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListLatestCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data          []*CommentItem         `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestCommentReply) Reset() {
	*x = ListLatestCommentReply{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestCommentReply) ProtoMessage() {}

func (x *ListLatestCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestCommentReply.ProtoReflect.Descriptor instead.
func (*ListLatestCommentReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{11}
}

func (x *ListLatestCommentReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListLatestCommentReply) GetData() []*CommentItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Browser       string                 `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ResourceId    int64                  `protobuf:"varint,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Group         []string               `protobuf:"bytes,8,rep,name=group,proto3" json:"group,omitempty"`
	HasAvatar     bool                   `protobuf:"varint,9,opt,name=hasAvatar,proto3" json:"hasAvatar,omitempty"`
	Cnname        string                 `protobuf:"bytes,10,opt,name=cnname,proto3" json:"cnname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_api_yyets_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_comment_proto_rawDescGZIP(), []int{12}
}

func (x *CommentItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CommentItem) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *CommentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentItem) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *CommentItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommentItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentItem) GetGroup() []string {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *CommentItem) GetHasAvatar() bool {
	if x != nil {
		return x.HasAvatar
	}
	return false
}

func (x *CommentItem) GetCnname() string {
	if x != nil {
		return x.Cnname
	}
	return ""
}

var File_api_yyets_v1_comment_proto protoreflect.FileDescriptor

const file_api_yyets_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/yyets/v1/comment.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xc1\x01\n" +
	"\x14CreateCommentRequest\x12(\n" +
	"\vresource_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"resourceId\x12\"\n" +
	"\acaptcha\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x04R\acaptcha\x12\x17\n" +
	"\x02id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18 R\x02id\x12#\n" +
	"\acontent\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18xR\acontent\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x05 \x01(\tR\tcommentId\"O\n" +
	"\x12CreateCommentReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x03R\n" +
	"statusCode\"\x16\n" +
	"\x14UpdateCommentRequest\"\x14\n" +
	"\x12UpdateCommentReply\"\x16\n" +
	"\x14DeleteCommentRequest\"\x14\n" +
	"\x12DeleteCommentReply\"\x13\n" +
	"\x11GetCommentRequest\"\x11\n" +
	"\x0fGetCommentReply\"\xa5\x01\n" +
	"\x12ListCommentRequest\x12(\n" +
	"\vresource_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"resourceId\x12\x1d\n" +
	"\x04size\x18\x02 \x01(\x03B\t\xfaB\x06\"\x04\x18x \x00R\x04size\x12\x1b\n" +
	"\x04page\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x04page\x12)\n" +
	"\x04sort\x18\x04 \x01(\tB\x15\xfaB\x12r\x10R\x06newestR\x06oldestR\x04sort\"x\n" +
	"\x10ListCommentReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.api.yyets.v1.CommentItemR\x04data\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\x03R\n" +
	"resourceId\"9\n" +
	"\x18ListLatestCommentRequest\x12\x1d\n" +
	"\x04size\x18\x01 \x01(\x03B\t\xfaB\x06\"\x04\x18x \x00R\x04size\"]\n" +
	"\x16ListLatestCommentReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.api.yyets.v1.CommentItemR\x04data\"\x82\x02\n" +
	"\vCommentItem\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x18\n" +
	"\abrowser\x18\x03 \x01(\tR\abrowser\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\x03R\n" +
	"resourceId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x14\n" +
	"\x05group\x18\b \x03(\tR\x05group\x12\x1c\n" +
	"\thasAvatar\x18\t \x01(\bR\thasAvatar\x12\x16\n" +
	"\x06cnname\x18\n" +
	" \x01(\tR\x06cnname2\xdc\x04\n" +
	"\aComment\x12n\n" +
	"\rCreateComment\x12\".api.yyets.v1.CreateCommentRequest\x1a .api.yyets.v1.CreateCommentReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/comment\x12U\n" +
	"\rUpdateComment\x12\".api.yyets.v1.UpdateCommentRequest\x1a .api.yyets.v1.UpdateCommentReply\x12U\n" +
	"\rDeleteComment\x12\".api.yyets.v1.DeleteCommentRequest\x1a .api.yyets.v1.DeleteCommentReply\x12L\n" +
	"\n" +
	"GetComment\x12\x1f.api.yyets.v1.GetCommentRequest\x1a\x1d.api.yyets.v1.GetCommentReply\x12e\n" +
	"\vListComment\x12 .api.yyets.v1.ListCommentRequest\x1a\x1e.api.yyets.v1.ListCommentReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/comment\x12~\n" +
	"\x11ListLatestComment\x12&.api.yyets.v1.ListLatestCommentRequest\x1a$.api.yyets.v1.ListLatestCommentReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/comment/newestB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_api_yyets_v1_comment_proto_rawDescOnce sync.Once
	file_api_yyets_v1_comment_proto_rawDescData []byte
)

func file_api_yyets_v1_comment_proto_rawDescGZIP() []byte {
	file_api_yyets_v1_comment_proto_rawDescOnce.Do(func() {
		file_api_yyets_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_yyets_v1_comment_proto_rawDesc), len(file_api_yyets_v1_comment_proto_rawDesc)))
	})
	return file_api_yyets_v1_comment_proto_rawDescData
}

var file_api_yyets_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_yyets_v1_comment_proto_goTypes = []any{
	(*CreateCommentRequest)(nil),     // 0: api.yyets.v1.CreateCommentRequest
	(*CreateCommentReply)(nil),       // 1: api.yyets.v1.CreateCommentReply
	(*UpdateCommentRequest)(nil),     // 2: api.yyets.v1.UpdateCommentRequest
	(*UpdateCommentReply)(nil),       // 3: api.yyets.v1.UpdateCommentReply
	(*DeleteCommentRequest)(nil),     // 4: api.yyets.v1.DeleteCommentRequest
	(*DeleteCommentReply)(nil),       // 5: api.yyets.v1.DeleteCommentReply
	(*GetCommentRequest)(nil),        // 6: api.yyets.v1.GetCommentRequest
	(*GetCommentReply)(nil),          // 7: api.yyets.v1.GetCommentReply
	(*ListCommentRequest)(nil),       // 8: api.yyets.v1.ListCommentRequest
	(*ListCommentReply)(nil),         // 9: api.yyets.v1.ListCommentReply
	(*ListLatestCommentRequest)(nil), // 10: api.yyets.v1.ListLatestCommentRequest
	(*ListLatestCommentReply)(nil),   // 11: api.yyets.v1.ListLatestCommentReply
	(*CommentItem)(nil),              // 12: api.yyets.v1.CommentItem
}
var file_api_yyets_v1_comment_proto_depIdxs = []int32{
	12, // 0: api.yyets.v1.ListCommentReply.data:type_name -> api.yyets.v1.CommentItem
	12, // 1: api.yyets.v1.ListLatestCommentReply.data:type_name -> api.yyets.v1.CommentItem
	0,  // 2: api.yyets.v1.Comment.CreateComment:input_type -> api.yyets.v1.CreateCommentRequest
	2,  // 3: api.yyets.v1.Comment.UpdateComment:input_type -> api.yyets.v1.UpdateCommentRequest
	4,  // 4: api.yyets.v1.Comment.DeleteComment:input_type -> api.yyets.v1.DeleteCommentRequest
	6,  // 5: api.yyets.v1.Comment.GetComment:input_type -> api.yyets.v1.GetCommentRequest
	8,  // 6: api.yyets.v1.Comment.ListComment:input_type -> api.yyets.v1.ListCommentRequest
	10, // 7: api.yyets.v1.Comment.ListLatestComment:input_type -> api.yyets.v1.ListLatestCommentRequest
	1,  // 8: api.yyets.v1.Comment.CreateComment:output_type -> api.yyets.v1.CreateCommentReply
	3,  // 9: api.yyets.v1.Comment.UpdateComment:output_type -> api.yyets.v1.UpdateCommentReply
	5,  // 10: api.yyets.v1.Comment.DeleteComment:output_type -> api.yyets.v1.DeleteCommentReply
	7,  // 11: api.yyets.v1.Comment.GetComment:output_type -> api.yyets.v1.GetCommentReply
	9,  // 12: api.yyets.v1.Comment.ListComment:output_type -> api.yyets.v1.ListCommentReply
	11, // 13: api.yyets.v1.Comment.ListLatestComment:output_type -> api.yyets.v1.ListLatestCommentReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_yyets_v1_comment_proto_init() }
func file_api_yyets_v1_comment_proto_init() {
	if File_api_yyets_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_yyets_v1_comment_proto_rawDesc), len(file_api_yyets_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_yyets_v1_comment_proto_goTypes,
		DependencyIndexes: file_api_yyets_v1_comment_proto_depIdxs,
		MessageInfos:      file_api_yyets_v1_comment_proto_msgTypes,
	}.Build()
	File_api_yyets_v1_comment_proto = out.File
	file_api_yyets_v1_comment_proto_goTypes = nil
	file_api_yyets_v1_comment_proto_depIdxs = nil
}
