// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: yyets/v1/douban.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDoubanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDoubanRequest) Reset() {
	*x = CreateDoubanRequest{}
	mi := &file_yyets_v1_douban_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoubanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoubanRequest) ProtoMessage() {}

func (x *CreateDoubanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoubanRequest.ProtoReflect.Descriptor instead.
func (*CreateDoubanRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{0}
}

type CreateDoubanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDoubanReply) Reset() {
	*x = CreateDoubanReply{}
	mi := &file_yyets_v1_douban_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoubanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoubanReply) ProtoMessage() {}

func (x *CreateDoubanReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoubanReply.ProtoReflect.Descriptor instead.
func (*CreateDoubanReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{1}
}

type UpdateDoubanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDoubanRequest) Reset() {
	*x = UpdateDoubanRequest{}
	mi := &file_yyets_v1_douban_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoubanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoubanRequest) ProtoMessage() {}

func (x *UpdateDoubanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoubanRequest.ProtoReflect.Descriptor instead.
func (*UpdateDoubanRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{2}
}

type UpdateDoubanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDoubanReply) Reset() {
	*x = UpdateDoubanReply{}
	mi := &file_yyets_v1_douban_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoubanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoubanReply) ProtoMessage() {}

func (x *UpdateDoubanReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoubanReply.ProtoReflect.Descriptor instead.
func (*UpdateDoubanReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{3}
}

type DeleteDoubanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoubanRequest) Reset() {
	*x = DeleteDoubanRequest{}
	mi := &file_yyets_v1_douban_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoubanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoubanRequest) ProtoMessage() {}

func (x *DeleteDoubanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoubanRequest.ProtoReflect.Descriptor instead.
func (*DeleteDoubanRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{4}
}

type DeleteDoubanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoubanReply) Reset() {
	*x = DeleteDoubanReply{}
	mi := &file_yyets_v1_douban_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoubanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoubanReply) ProtoMessage() {}

func (x *DeleteDoubanReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoubanReply.ProtoReflect.Descriptor instead.
func (*DeleteDoubanReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{5}
}

type GetDoubanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoubanRequest) Reset() {
	*x = GetDoubanRequest{}
	mi := &file_yyets_v1_douban_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoubanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoubanRequest) ProtoMessage() {}

func (x *GetDoubanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoubanRequest.ProtoReflect.Descriptor instead.
func (*GetDoubanRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{6}
}

func (x *GetDoubanRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type GetDoubanReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DoubanId        int64                  `protobuf:"varint,2,opt,name=douban_id,json=doubanId,proto3" json:"douban_id,omitempty"`
	DoubanLink      string                 `protobuf:"bytes,3,opt,name=douban_link,json=doubanLink,proto3" json:"douban_link,omitempty"`
	PosterLink      string                 `protobuf:"bytes,4,opt,name=poster_link,json=posterLink,proto3" json:"poster_link,omitempty"`
	ResourceId      int64                  `protobuf:"varint,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Rating          string                 `protobuf:"bytes,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Actors          []string               `protobuf:"bytes,7,rep,name=actors,proto3" json:"actors,omitempty"`
	Directors       []string               `protobuf:"bytes,8,rep,name=directors,proto3" json:"directors,omitempty"`
	Genre           []string               `protobuf:"bytes,9,rep,name=genre,proto3" json:"genre,omitempty"`
	ReleaseDate     string                 `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	EpisodeCount    string                 `protobuf:"bytes,11,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	EpisodeDuration string                 `protobuf:"bytes,12,opt,name=episode_duration,json=episodeDuration,proto3" json:"episode_duration,omitempty"`
	Writers         []string               `protobuf:"bytes,13,rep,name=writers,proto3" json:"writers,omitempty"`
	Year            string                 `protobuf:"bytes,14,opt,name=year,proto3" json:"year,omitempty"`
	Introduction    string                 `protobuf:"bytes,15,opt,name=introduction,proto3" json:"introduction,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDoubanReply) Reset() {
	*x = GetDoubanReply{}
	mi := &file_yyets_v1_douban_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoubanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoubanReply) ProtoMessage() {}

func (x *GetDoubanReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoubanReply.ProtoReflect.Descriptor instead.
func (*GetDoubanReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{7}
}

func (x *GetDoubanReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDoubanReply) GetDoubanId() int64 {
	if x != nil {
		return x.DoubanId
	}
	return 0
}

func (x *GetDoubanReply) GetDoubanLink() string {
	if x != nil {
		return x.DoubanLink
	}
	return ""
}

func (x *GetDoubanReply) GetPosterLink() string {
	if x != nil {
		return x.PosterLink
	}
	return ""
}

func (x *GetDoubanReply) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *GetDoubanReply) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *GetDoubanReply) GetActors() []string {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *GetDoubanReply) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *GetDoubanReply) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *GetDoubanReply) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *GetDoubanReply) GetEpisodeCount() string {
	if x != nil {
		return x.EpisodeCount
	}
	return ""
}

func (x *GetDoubanReply) GetEpisodeDuration() string {
	if x != nil {
		return x.EpisodeDuration
	}
	return ""
}

func (x *GetDoubanReply) GetWriters() []string {
	if x != nil {
		return x.Writers
	}
	return nil
}

func (x *GetDoubanReply) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *GetDoubanReply) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

type ListDoubanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoubanRequest) Reset() {
	*x = ListDoubanRequest{}
	mi := &file_yyets_v1_douban_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoubanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoubanRequest) ProtoMessage() {}

func (x *ListDoubanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoubanRequest.ProtoReflect.Descriptor instead.
func (*ListDoubanRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{8}
}

type ListDoubanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoubanReply) Reset() {
	*x = ListDoubanReply{}
	mi := &file_yyets_v1_douban_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoubanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoubanReply) ProtoMessage() {}

func (x *ListDoubanReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_douban_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoubanReply.ProtoReflect.Descriptor instead.
func (*ListDoubanReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_douban_proto_rawDescGZIP(), []int{9}
}

var File_yyets_v1_douban_proto protoreflect.FileDescriptor

const file_yyets_v1_douban_proto_rawDesc = "" +
	"\n" +
	"\x15yyets/v1/douban.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\"\x15\n" +
	"\x13CreateDoubanRequest\"\x13\n" +
	"\x11CreateDoubanReply\"\x15\n" +
	"\x13UpdateDoubanRequest\"\x13\n" +
	"\x11UpdateDoubanReply\"\x15\n" +
	"\x13DeleteDoubanRequest\"\x13\n" +
	"\x11DeleteDoubanReply\"3\n" +
	"\x10GetDoubanRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\x03R\n" +
	"resourceId\"\xcd\x03\n" +
	"\x0eGetDoubanReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdouban_id\x18\x02 \x01(\x03R\bdoubanId\x12\x1f\n" +
	"\vdouban_link\x18\x03 \x01(\tR\n" +
	"doubanLink\x12\x1f\n" +
	"\vposter_link\x18\x04 \x01(\tR\n" +
	"posterLink\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\x03R\n" +
	"resourceId\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\tR\x06rating\x12\x16\n" +
	"\x06actors\x18\a \x03(\tR\x06actors\x12\x1c\n" +
	"\tdirectors\x18\b \x03(\tR\tdirectors\x12\x14\n" +
	"\x05genre\x18\t \x03(\tR\x05genre\x12!\n" +
	"\frelease_date\x18\n" +
	" \x01(\tR\vreleaseDate\x12#\n" +
	"\repisode_count\x18\v \x01(\tR\fepisodeCount\x12)\n" +
	"\x10episode_duration\x18\f \x01(\tR\x0fepisodeDuration\x12\x18\n" +
	"\awriters\x18\r \x03(\tR\awriters\x12\x12\n" +
	"\x04year\x18\x0e \x01(\tR\x04year\x12\"\n" +
	"\fintroduction\x18\x0f \x01(\tR\fintroduction\"\x13\n" +
	"\x11ListDoubanRequest\"\x11\n" +
	"\x0fListDoubanReply2\xb2\x03\n" +
	"\x06Douban\x12R\n" +
	"\fCreateDouban\x12!.api.yyets.v1.CreateDoubanRequest\x1a\x1f.api.yyets.v1.CreateDoubanReply\x12R\n" +
	"\fUpdateDouban\x12!.api.yyets.v1.UpdateDoubanRequest\x1a\x1f.api.yyets.v1.UpdateDoubanReply\x12R\n" +
	"\fDeleteDouban\x12!.api.yyets.v1.DeleteDoubanRequest\x1a\x1f.api.yyets.v1.DeleteDoubanReply\x12^\n" +
	"\tGetDouban\x12\x1e.api.yyets.v1.GetDoubanRequest\x1a\x1c.api.yyets.v1.GetDoubanReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/douban\x12L\n" +
	"\n" +
	"ListDouban\x12\x1f.api.yyets.v1.ListDoubanRequest\x1a\x1d.api.yyets.v1.ListDoubanReplyB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_yyets_v1_douban_proto_rawDescOnce sync.Once
	file_yyets_v1_douban_proto_rawDescData []byte
)

func file_yyets_v1_douban_proto_rawDescGZIP() []byte {
	file_yyets_v1_douban_proto_rawDescOnce.Do(func() {
		file_yyets_v1_douban_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yyets_v1_douban_proto_rawDesc), len(file_yyets_v1_douban_proto_rawDesc)))
	})
	return file_yyets_v1_douban_proto_rawDescData
}

var file_yyets_v1_douban_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_yyets_v1_douban_proto_goTypes = []any{
	(*CreateDoubanRequest)(nil), // 0: api.yyets.v1.CreateDoubanRequest
	(*CreateDoubanReply)(nil),   // 1: api.yyets.v1.CreateDoubanReply
	(*UpdateDoubanRequest)(nil), // 2: api.yyets.v1.UpdateDoubanRequest
	(*UpdateDoubanReply)(nil),   // 3: api.yyets.v1.UpdateDoubanReply
	(*DeleteDoubanRequest)(nil), // 4: api.yyets.v1.DeleteDoubanRequest
	(*DeleteDoubanReply)(nil),   // 5: api.yyets.v1.DeleteDoubanReply
	(*GetDoubanRequest)(nil),    // 6: api.yyets.v1.GetDoubanRequest
	(*GetDoubanReply)(nil),      // 7: api.yyets.v1.GetDoubanReply
	(*ListDoubanRequest)(nil),   // 8: api.yyets.v1.ListDoubanRequest
	(*ListDoubanReply)(nil),     // 9: api.yyets.v1.ListDoubanReply
}
var file_yyets_v1_douban_proto_depIdxs = []int32{
	0, // 0: api.yyets.v1.Douban.CreateDouban:input_type -> api.yyets.v1.CreateDoubanRequest
	2, // 1: api.yyets.v1.Douban.UpdateDouban:input_type -> api.yyets.v1.UpdateDoubanRequest
	4, // 2: api.yyets.v1.Douban.DeleteDouban:input_type -> api.yyets.v1.DeleteDoubanRequest
	6, // 3: api.yyets.v1.Douban.GetDouban:input_type -> api.yyets.v1.GetDoubanRequest
	8, // 4: api.yyets.v1.Douban.ListDouban:input_type -> api.yyets.v1.ListDoubanRequest
	1, // 5: api.yyets.v1.Douban.CreateDouban:output_type -> api.yyets.v1.CreateDoubanReply
	3, // 6: api.yyets.v1.Douban.UpdateDouban:output_type -> api.yyets.v1.UpdateDoubanReply
	5, // 7: api.yyets.v1.Douban.DeleteDouban:output_type -> api.yyets.v1.DeleteDoubanReply
	7, // 8: api.yyets.v1.Douban.GetDouban:output_type -> api.yyets.v1.GetDoubanReply
	9, // 9: api.yyets.v1.Douban.ListDouban:output_type -> api.yyets.v1.ListDoubanReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yyets_v1_douban_proto_init() }
func file_yyets_v1_douban_proto_init() {
	if File_yyets_v1_douban_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yyets_v1_douban_proto_rawDesc), len(file_yyets_v1_douban_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yyets_v1_douban_proto_goTypes,
		DependencyIndexes: file_yyets_v1_douban_proto_depIdxs,
		MessageInfos:      file_yyets_v1_douban_proto_msgTypes,
	}.Build()
	File_yyets_v1_douban_proto = out.File
	file_yyets_v1_douban_proto_goTypes = nil
	file_yyets_v1_douban_proto_depIdxs = nil
}
