// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/yyets/v1/notification.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{0}
}

type CreateNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationReply) Reset() {
	*x = CreateNotificationReply{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationReply) ProtoMessage() {}

func (x *CreateNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationReply.ProtoReflect.Descriptor instead.
func (*CreateNotificationReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{1}
}

type UpdateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{2}
}

type UpdateNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationReply) Reset() {
	*x = UpdateNotificationReply{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationReply) ProtoMessage() {}

func (x *UpdateNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationReply.ProtoReflect.Descriptor instead.
func (*UpdateNotificationReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{3}
}

type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{4}
}

type DeleteNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationReply) Reset() {
	*x = DeleteNotificationReply{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationReply) ProtoMessage() {}

func (x *DeleteNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationReply.ProtoReflect.Descriptor instead.
func (*DeleteNotificationReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{5}
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotificationRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNotificationRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type NotificationItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Browser        string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Id             string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	ReplyToContent string                 `protobuf:"bytes,5,opt,name=reply_to_content,proto3" json:"reply_to_content,omitempty"`
	ReplyToId      string                 `protobuf:"bytes,6,opt,name=reply_to_id,proto3" json:"reply_to_id,omitempty"`
	Type           string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Username       string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *NotificationItem) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *NotificationItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NotificationItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationItem) GetReplyToContent() string {
	if x != nil {
		return x.ReplyToContent
	}
	return ""
}

func (x *NotificationItem) GetReplyToId() string {
	if x != nil {
		return x.ReplyToId
	}
	return ""
}

func (x *NotificationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadCount     int32                  `protobuf:"varint,1,opt,name=read_count,proto3" json:"read_count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,proto3" json:"unread_count,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	ReadItem      []*NotificationItem    `protobuf:"bytes,4,rep,name=read_item,proto3" json:"read_item,omitempty"`
	UnreadItem    []*NotificationItem    `protobuf:"bytes,5,rep,name=unread_item,proto3" json:"unread_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationReply) Reset() {
	*x = GetNotificationReply{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationReply) ProtoMessage() {}

func (x *GetNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationReply.ProtoReflect.Descriptor instead.
func (*GetNotificationReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotificationReply) GetReadCount() int32 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *GetNotificationReply) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *GetNotificationReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetNotificationReply) GetReadItem() []*NotificationItem {
	if x != nil {
		return x.ReadItem
	}
	return nil
}

func (x *GetNotificationReply) GetUnreadItem() []*NotificationItem {
	if x != nil {
		return x.UnreadItem
	}
	return nil
}

type ListNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationRequest) Reset() {
	*x = ListNotificationRequest{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationRequest) ProtoMessage() {}

func (x *ListNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{9}
}

type ListNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationReply) Reset() {
	*x = ListNotificationReply{}
	mi := &file_api_yyets_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationReply) ProtoMessage() {}

func (x *ListNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_yyets_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationReply.ProtoReflect.Descriptor instead.
func (*ListNotificationReply) Descriptor() ([]byte, []int) {
	return file_api_yyets_v1_notification_proto_rawDescGZIP(), []int{10}
}

var File_api_yyets_v1_notification_proto protoreflect.FileDescriptor

const file_api_yyets_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/yyets/v1/notification.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\"\x1b\n" +
	"\x19CreateNotificationRequest\"\x19\n" +
	"\x17CreateNotificationReply\"\x1b\n" +
	"\x19UpdateNotificationRequest\"\x19\n" +
	"\x17UpdateNotificationReply\"\x1b\n" +
	"\x19DeleteNotificationRequest\"\x19\n" +
	"\x17DeleteNotificationReply\"@\n" +
	"\x16GetNotificationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xe8\x01\n" +
	"\x10NotificationItem\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12*\n" +
	"\x10reply_to_content\x18\x05 \x01(\tR\x10reply_to_content\x12 \n" +
	"\vreply_to_id\x18\x06 \x01(\tR\vreply_to_id\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\"\xf6\x01\n" +
	"\x14GetNotificationReply\x12\x1e\n" +
	"\n" +
	"read_count\x18\x01 \x01(\x05R\n" +
	"read_count\x12\"\n" +
	"\funread_count\x18\x02 \x01(\x05R\funread_count\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12<\n" +
	"\tread_item\x18\x04 \x03(\v2\x1e.api.yyets.v1.NotificationItemR\tread_item\x12@\n" +
	"\vunread_item\x18\x05 \x03(\v2\x1e.api.yyets.v1.NotificationItemR\vunread_item\"\x19\n" +
	"\x17ListNotificationRequest\"\x17\n" +
	"\x15ListNotificationReply2\x98\x04\n" +
	"\fNotification\x12d\n" +
	"\x12CreateNotification\x12'.api.yyets.v1.CreateNotificationRequest\x1a%.api.yyets.v1.CreateNotificationReply\x12d\n" +
	"\x12UpdateNotification\x12'.api.yyets.v1.UpdateNotificationRequest\x1a%.api.yyets.v1.UpdateNotificationReply\x12d\n" +
	"\x12DeleteNotification\x12'.api.yyets.v1.DeleteNotificationRequest\x1a%.api.yyets.v1.DeleteNotificationReply\x12v\n" +
	"\x0fGetNotification\x12$.api.yyets.v1.GetNotificationRequest\x1a\".api.yyets.v1.GetNotificationReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/notification\x12^\n" +
	"\x10ListNotification\x12%.api.yyets.v1.ListNotificationRequest\x1a#.api.yyets.v1.ListNotificationReplyB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_api_yyets_v1_notification_proto_rawDescOnce sync.Once
	file_api_yyets_v1_notification_proto_rawDescData []byte
)

func file_api_yyets_v1_notification_proto_rawDescGZIP() []byte {
	file_api_yyets_v1_notification_proto_rawDescOnce.Do(func() {
		file_api_yyets_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_yyets_v1_notification_proto_rawDesc), len(file_api_yyets_v1_notification_proto_rawDesc)))
	})
	return file_api_yyets_v1_notification_proto_rawDescData
}

var file_api_yyets_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_yyets_v1_notification_proto_goTypes = []any{
	(*CreateNotificationRequest)(nil), // 0: api.yyets.v1.CreateNotificationRequest
	(*CreateNotificationReply)(nil),   // 1: api.yyets.v1.CreateNotificationReply
	(*UpdateNotificationRequest)(nil), // 2: api.yyets.v1.UpdateNotificationRequest
	(*UpdateNotificationReply)(nil),   // 3: api.yyets.v1.UpdateNotificationReply
	(*DeleteNotificationRequest)(nil), // 4: api.yyets.v1.DeleteNotificationRequest
	(*DeleteNotificationReply)(nil),   // 5: api.yyets.v1.DeleteNotificationReply
	(*GetNotificationRequest)(nil),    // 6: api.yyets.v1.GetNotificationRequest
	(*NotificationItem)(nil),          // 7: api.yyets.v1.NotificationItem
	(*GetNotificationReply)(nil),      // 8: api.yyets.v1.GetNotificationReply
	(*ListNotificationRequest)(nil),   // 9: api.yyets.v1.ListNotificationRequest
	(*ListNotificationReply)(nil),     // 10: api.yyets.v1.ListNotificationReply
}
var file_api_yyets_v1_notification_proto_depIdxs = []int32{
	7,  // 0: api.yyets.v1.GetNotificationReply.read_item:type_name -> api.yyets.v1.NotificationItem
	7,  // 1: api.yyets.v1.GetNotificationReply.unread_item:type_name -> api.yyets.v1.NotificationItem
	0,  // 2: api.yyets.v1.Notification.CreateNotification:input_type -> api.yyets.v1.CreateNotificationRequest
	2,  // 3: api.yyets.v1.Notification.UpdateNotification:input_type -> api.yyets.v1.UpdateNotificationRequest
	4,  // 4: api.yyets.v1.Notification.DeleteNotification:input_type -> api.yyets.v1.DeleteNotificationRequest
	6,  // 5: api.yyets.v1.Notification.GetNotification:input_type -> api.yyets.v1.GetNotificationRequest
	9,  // 6: api.yyets.v1.Notification.ListNotification:input_type -> api.yyets.v1.ListNotificationRequest
	1,  // 7: api.yyets.v1.Notification.CreateNotification:output_type -> api.yyets.v1.CreateNotificationReply
	3,  // 8: api.yyets.v1.Notification.UpdateNotification:output_type -> api.yyets.v1.UpdateNotificationReply
	5,  // 9: api.yyets.v1.Notification.DeleteNotification:output_type -> api.yyets.v1.DeleteNotificationReply
	8,  // 10: api.yyets.v1.Notification.GetNotification:output_type -> api.yyets.v1.GetNotificationReply
	10, // 11: api.yyets.v1.Notification.ListNotification:output_type -> api.yyets.v1.ListNotificationReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_yyets_v1_notification_proto_init() }
func file_api_yyets_v1_notification_proto_init() {
	if File_api_yyets_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_yyets_v1_notification_proto_rawDesc), len(file_api_yyets_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_yyets_v1_notification_proto_goTypes,
		DependencyIndexes: file_api_yyets_v1_notification_proto_depIdxs,
		MessageInfos:      file_api_yyets_v1_notification_proto_msgTypes,
	}.Build()
	File_api_yyets_v1_notification_proto = out.File
	file_api_yyets_v1_notification_proto_goTypes = nil
	file_api_yyets_v1_notification_proto_depIdxs = nil
}
