// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: yyets/v1/resource.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceDataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cnname        string                 `protobuf:"bytes,2,opt,name=cnname,proto3" json:"cnname,omitempty"`
	Enname        string                 `protobuf:"bytes,3,opt,name=enname,proto3" json:"enname,omitempty"`
	Aliasname     string                 `protobuf:"bytes,4,opt,name=aliasname,proto3" json:"aliasname,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	ChannelCn     string                 `protobuf:"bytes,6,opt,name=channel_cn,json=channelCn,proto3" json:"channel_cn,omitempty"`
	Area          string                 `protobuf:"bytes,7,opt,name=area,proto3" json:"area,omitempty"`
	ShowType      string                 `protobuf:"bytes,8,opt,name=show_type,json=showType,proto3" json:"show_type,omitempty"`
	Expire        string                 `protobuf:"bytes,9,opt,name=expire,proto3" json:"expire,omitempty"`
	Views         int64                  `protobuf:"varint,10,opt,name=views,proto3" json:"views,omitempty"`
	Year          []int64                `protobuf:"varint,11,rep,packed,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDataInfo) Reset() {
	*x = ResourceDataInfo{}
	mi := &file_yyets_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDataInfo) ProtoMessage() {}

func (x *ResourceDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDataInfo.ProtoReflect.Descriptor instead.
func (*ResourceDataInfo) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceDataInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResourceDataInfo) GetCnname() string {
	if x != nil {
		return x.Cnname
	}
	return ""
}

func (x *ResourceDataInfo) GetEnname() string {
	if x != nil {
		return x.Enname
	}
	return ""
}

func (x *ResourceDataInfo) GetAliasname() string {
	if x != nil {
		return x.Aliasname
	}
	return ""
}

func (x *ResourceDataInfo) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ResourceDataInfo) GetChannelCn() string {
	if x != nil {
		return x.ChannelCn
	}
	return ""
}

func (x *ResourceDataInfo) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ResourceDataInfo) GetShowType() string {
	if x != nil {
		return x.ShowType
	}
	return ""
}

func (x *ResourceDataInfo) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

func (x *ResourceDataInfo) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *ResourceDataInfo) GetYear() []int64 {
	if x != nil {
		return x.Year
	}
	return nil
}

type ResourceFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Way           string                 `protobuf:"bytes,1,opt,name=way,proto3" json:"way,omitempty"`
	WayCn         string                 `protobuf:"bytes,2,opt,name=way_cn,json=wayCn,proto3" json:"way_cn,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Passwd        string                 `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceFile) Reset() {
	*x = ResourceFile{}
	mi := &file_yyets_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceFile) ProtoMessage() {}

func (x *ResourceFile) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceFile.ProtoReflect.Descriptor instead.
func (*ResourceFile) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceFile) GetWay() string {
	if x != nil {
		return x.Way
	}
	return ""
}

func (x *ResourceFile) GetWayCn() string {
	if x != nil {
		return x.WayCn
	}
	return ""
}

func (x *ResourceFile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ResourceFile) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

type ResourceSeasonItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Episode       string                 `protobuf:"bytes,2,opt,name=episode,proto3" json:"episode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	YyetsTrans    int64                  `protobuf:"varint,5,opt,name=yyets_trans,json=yyetsTrans,proto3" json:"yyets_trans,omitempty"`
	Dateline      string                 `protobuf:"bytes,6,opt,name=dateline,proto3" json:"dateline,omitempty"`
	Files         []*ResourceFile        `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSeasonItem) Reset() {
	*x = ResourceSeasonItem{}
	mi := &file_yyets_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSeasonItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSeasonItem) ProtoMessage() {}

func (x *ResourceSeasonItem) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSeasonItem.ProtoReflect.Descriptor instead.
func (*ResourceSeasonItem) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceSeasonItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ResourceSeasonItem) GetEpisode() string {
	if x != nil {
		return x.Episode
	}
	return ""
}

func (x *ResourceSeasonItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceSeasonItem) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ResourceSeasonItem) GetYyetsTrans() int64 {
	if x != nil {
		return x.YyetsTrans
	}
	return 0
}

func (x *ResourceSeasonItem) GetDateline() string {
	if x != nil {
		return x.Dateline
	}
	return ""
}

func (x *ResourceSeasonItem) GetFiles() []*ResourceFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type ResourceSeasonList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResourceSeasonItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSeasonList) Reset() {
	*x = ResourceSeasonList{}
	mi := &file_yyets_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSeasonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSeasonList) ProtoMessage() {}

func (x *ResourceSeasonList) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSeasonList.ProtoReflect.Descriptor instead.
func (*ResourceSeasonList) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceSeasonList) GetItems() []*ResourceSeasonItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ResourceSeason struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	SeasonNum     string                         `protobuf:"bytes,1,opt,name=season_num,json=seasonNum,proto3" json:"season_num,omitempty"`
	SeasonCn      string                         `protobuf:"bytes,2,opt,name=season_cn,json=seasonCn,proto3" json:"season_cn,omitempty"`
	Items         map[string]*ResourceSeasonList `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Formats       []string                       `protobuf:"bytes,4,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSeason) Reset() {
	*x = ResourceSeason{}
	mi := &file_yyets_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSeason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSeason) ProtoMessage() {}

func (x *ResourceSeason) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSeason.ProtoReflect.Descriptor instead.
func (*ResourceSeason) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceSeason) GetSeasonNum() string {
	if x != nil {
		return x.SeasonNum
	}
	return ""
}

func (x *ResourceSeason) GetSeasonCn() string {
	if x != nil {
		return x.SeasonCn
	}
	return ""
}

func (x *ResourceSeason) GetItems() map[string]*ResourceSeasonList {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ResourceSeason) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

type ResourceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ResourceDataInfo      `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	List          []*ResourceSeason      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceData) Reset() {
	*x = ResourceData{}
	mi := &file_yyets_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceData) ProtoMessage() {}

func (x *ResourceData) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceData.ProtoReflect.Descriptor instead.
func (*ResourceData) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceData) GetInfo() *ResourceDataInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ResourceData) GetList() []*ResourceSeason {
	if x != nil {
		return x.List
	}
	return nil
}

type ResourceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ResourceData          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceItem) Reset() {
	*x = ResourceItem{}
	mi := &file_yyets_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceItem) ProtoMessage() {}

func (x *ResourceItem) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceItem.ProtoReflect.Descriptor instead.
func (*ResourceItem) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceItem) GetData() *ResourceData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResourceClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ALL           map[string]string      `protobuf:"bytes,1,rep,name=ALL,proto3" json:"ALL,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JP            string                 `protobuf:"bytes,2,opt,name=JP,proto3" json:"JP,omitempty"`
	US            string                 `protobuf:"bytes,3,opt,name=US,proto3" json:"US,omitempty"`
	UK            string                 `protobuf:"bytes,4,opt,name=UK,proto3" json:"UK,omitempty"`
	KR            string                 `protobuf:"bytes,5,opt,name=KR,proto3" json:"KR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceClass) Reset() {
	*x = ResourceClass{}
	mi := &file_yyets_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceClass) ProtoMessage() {}

func (x *ResourceClass) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceClass.ProtoReflect.Descriptor instead.
func (*ResourceClass) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceClass) GetALL() map[string]string {
	if x != nil {
		return x.ALL
	}
	return nil
}

func (x *ResourceClass) GetJP() string {
	if x != nil {
		return x.JP
	}
	return ""
}

func (x *ResourceClass) GetUS() string {
	if x != nil {
		return x.US
	}
	return ""
}

func (x *ResourceClass) GetUK() string {
	if x != nil {
		return x.UK
	}
	return ""
}

func (x *ResourceClass) GetKR() string {
	if x != nil {
		return x.KR
	}
	return ""
}

type TopResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopResourceRequest) Reset() {
	*x = TopResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopResourceRequest) ProtoMessage() {}

func (x *TopResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopResourceRequest.ProtoReflect.Descriptor instead.
func (*TopResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{8}
}

type TopResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ALL           []*ResourceItem        `protobuf:"bytes,1,rep,name=ALL,proto3" json:"ALL,omitempty"`
	US            []*ResourceItem        `protobuf:"bytes,2,rep,name=US,proto3" json:"US,omitempty"`
	JP            []*ResourceItem        `protobuf:"bytes,3,rep,name=JP,proto3" json:"JP,omitempty"`
	KR            []*ResourceItem        `protobuf:"bytes,4,rep,name=KR,proto3" json:"KR,omitempty"`
	UK            []*ResourceItem        `protobuf:"bytes,5,rep,name=UK,proto3" json:"UK,omitempty"`
	Class         *ResourceClass         `protobuf:"bytes,6,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopResourceReply) Reset() {
	*x = TopResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopResourceReply) ProtoMessage() {}

func (x *TopResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopResourceReply.ProtoReflect.Descriptor instead.
func (*TopResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{9}
}

func (x *TopResourceReply) GetALL() []*ResourceItem {
	if x != nil {
		return x.ALL
	}
	return nil
}

func (x *TopResourceReply) GetUS() []*ResourceItem {
	if x != nil {
		return x.US
	}
	return nil
}

func (x *TopResourceReply) GetJP() []*ResourceItem {
	if x != nil {
		return x.JP
	}
	return nil
}

func (x *TopResourceReply) GetKR() []*ResourceItem {
	if x != nil {
		return x.KR
	}
	return nil
}

func (x *TopResourceReply) GetUK() []*ResourceItem {
	if x != nil {
		return x.UK
	}
	return nil
}

func (x *TopResourceReply) GetClass() *ResourceClass {
	if x != nil {
		return x.Class
	}
	return nil
}

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{10}
}

type CreateResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceReply) Reset() {
	*x = CreateResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceReply) ProtoMessage() {}

func (x *CreateResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceReply.ProtoReflect.Descriptor instead.
func (*CreateResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{11}
}

type UpdateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{12}
}

type UpdateResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceReply) Reset() {
	*x = UpdateResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceReply) ProtoMessage() {}

func (x *UpdateResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceReply.ProtoReflect.Descriptor instead.
func (*UpdateResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{13}
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{14}
}

type DeleteResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceReply) Reset() {
	*x = DeleteResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceReply) ProtoMessage() {}

func (x *DeleteResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceReply.ProtoReflect.Descriptor instead.
func (*DeleteResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{15}
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{16}
}

func (x *GetResourceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cnname        string                 `protobuf:"bytes,2,opt,name=cnname,proto3" json:"cnname,omitempty"`
	Enname        string                 `protobuf:"bytes,3,opt,name=enname,proto3" json:"enname,omitempty"`
	Aliasname     string                 `protobuf:"bytes,4,opt,name=aliasname,proto3" json:"aliasname,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Views         int64                  `protobuf:"varint,6,opt,name=views,proto3" json:"views,omitempty"`
	Data          *ResourceData          `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceReply) Reset() {
	*x = GetResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceReply) ProtoMessage() {}

func (x *GetResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceReply.ProtoReflect.Descriptor instead.
func (*GetResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{17}
}

func (x *GetResourceReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetResourceReply) GetCnname() string {
	if x != nil {
		return x.Cnname
	}
	return ""
}

func (x *GetResourceReply) GetEnname() string {
	if x != nil {
		return x.Enname
	}
	return ""
}

func (x *GetResourceReply) GetAliasname() string {
	if x != nil {
		return x.Aliasname
	}
	return ""
}

func (x *GetResourceReply) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *GetResourceReply) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetResourceReply) GetData() *ResourceData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceRequest) Reset() {
	*x = ListResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceRequest) ProtoMessage() {}

func (x *ListResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceRequest.ProtoReflect.Descriptor instead.
func (*ListResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{18}
}

type ListResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceReply) Reset() {
	*x = ListResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceReply) ProtoMessage() {}

func (x *ListResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceReply.ProtoReflect.Descriptor instead.
func (*ListResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{19}
}

type SearchResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourceRequest) Reset() {
	*x = SearchResourceRequest{}
	mi := &file_yyets_v1_resource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourceRequest) ProtoMessage() {}

func (x *SearchResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourceRequest.ProtoReflect.Descriptor instead.
func (*SearchResourceRequest) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{20}
}

func (x *SearchResourceRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchResourceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SearchResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      []*ResourceDataInfo    `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	Comment       []*SearchComment       `protobuf:"bytes,2,rep,name=comment,proto3" json:"comment,omitempty"`
	Subtitle      []*SearchSubtitle      `protobuf:"bytes,3,rep,name=subtitle,proto3" json:"subtitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourceReply) Reset() {
	*x = SearchResourceReply{}
	mi := &file_yyets_v1_resource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourceReply) ProtoMessage() {}

func (x *SearchResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourceReply.ProtoReflect.Descriptor instead.
func (*SearchResourceReply) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{21}
}

func (x *SearchResourceReply) GetResource() []*ResourceDataInfo {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *SearchResourceReply) GetComment() []*SearchComment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *SearchResourceReply) GetSubtitle() []*SearchSubtitle {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

type SearchComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	CommentID     string                 `protobuf:"bytes,4,opt,name=commentID,proto3" json:"commentID,omitempty"`
	ResourceID    int64                  `protobuf:"varint,5,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	ResourceName  string                 `protobuf:"bytes,6,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Origin        string                 `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	HasAvatar     bool                   `protobuf:"varint,8,opt,name=hasAvatar,proto3" json:"hasAvatar,omitempty"`
	Hash          string                 `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchComment) Reset() {
	*x = SearchComment{}
	mi := &file_yyets_v1_resource_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchComment) ProtoMessage() {}

func (x *SearchComment) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchComment.ProtoReflect.Descriptor instead.
func (*SearchComment) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{22}
}

func (x *SearchComment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchComment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SearchComment) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SearchComment) GetCommentID() string {
	if x != nil {
		return x.CommentID
	}
	return ""
}

func (x *SearchComment) GetResourceID() int64 {
	if x != nil {
		return x.ResourceID
	}
	return 0
}

func (x *SearchComment) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *SearchComment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SearchComment) GetHasAvatar() bool {
	if x != nil {
		return x.HasAvatar
	}
	return false
}

func (x *SearchComment) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type SearchSubtitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSubtitle) Reset() {
	*x = SearchSubtitle{}
	mi := &file_yyets_v1_resource_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSubtitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSubtitle) ProtoMessage() {}

func (x *SearchSubtitle) ProtoReflect() protoreflect.Message {
	mi := &file_yyets_v1_resource_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSubtitle.ProtoReflect.Descriptor instead.
func (*SearchSubtitle) Descriptor() ([]byte, []int) {
	return file_yyets_v1_resource_proto_rawDescGZIP(), []int{23}
}

var File_yyets_v1_resource_proto protoreflect.FileDescriptor

const file_yyets_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x17yyets/v1/resource.proto\x12\fapi.yyets.v1\x1a\x1cgoogle/api/annotations.proto\"\x9c\x02\n" +
	"\x10ResourceDataInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06cnname\x18\x02 \x01(\tR\x06cnname\x12\x16\n" +
	"\x06enname\x18\x03 \x01(\tR\x06enname\x12\x1c\n" +
	"\taliasname\x18\x04 \x01(\tR\taliasname\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"channel_cn\x18\x06 \x01(\tR\tchannelCn\x12\x12\n" +
	"\x04area\x18\a \x01(\tR\x04area\x12\x1b\n" +
	"\tshow_type\x18\b \x01(\tR\bshowType\x12\x16\n" +
	"\x06expire\x18\t \x01(\tR\x06expire\x12\x14\n" +
	"\x05views\x18\n" +
	" \x01(\x03R\x05views\x12\x12\n" +
	"\x04year\x18\v \x03(\x03R\x04year\"i\n" +
	"\fResourceFile\x12\x10\n" +
	"\x03way\x18\x01 \x01(\tR\x03way\x12\x15\n" +
	"\x06way_cn\x18\x02 \x01(\tR\x05wayCn\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06passwd\x18\x04 \x01(\tR\x06passwd\"\xde\x01\n" +
	"\x12ResourceSeasonItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aepisode\x18\x02 \x01(\tR\aepisode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x1f\n" +
	"\vyyets_trans\x18\x05 \x01(\x03R\n" +
	"yyetsTrans\x12\x1a\n" +
	"\bdateline\x18\x06 \x01(\tR\bdateline\x120\n" +
	"\x05files\x18\a \x03(\v2\x1a.api.yyets.v1.ResourceFileR\x05files\"L\n" +
	"\x12ResourceSeasonList\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .api.yyets.v1.ResourceSeasonItemR\x05items\"\x81\x02\n" +
	"\x0eResourceSeason\x12\x1d\n" +
	"\n" +
	"season_num\x18\x01 \x01(\tR\tseasonNum\x12\x1b\n" +
	"\tseason_cn\x18\x02 \x01(\tR\bseasonCn\x12=\n" +
	"\x05items\x18\x03 \x03(\v2'.api.yyets.v1.ResourceSeason.ItemsEntryR\x05items\x12\x18\n" +
	"\aformats\x18\x04 \x03(\tR\aformats\x1aZ\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .api.yyets.v1.ResourceSeasonListR\x05value:\x028\x01\"t\n" +
	"\fResourceData\x122\n" +
	"\x04info\x18\x01 \x01(\v2\x1e.api.yyets.v1.ResourceDataInfoR\x04info\x120\n" +
	"\x04list\x18\x02 \x03(\v2\x1c.api.yyets.v1.ResourceSeasonR\x04list\">\n" +
	"\fResourceItem\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.api.yyets.v1.ResourceDataR\x04data\"\xbf\x01\n" +
	"\rResourceClass\x126\n" +
	"\x03ALL\x18\x01 \x03(\v2$.api.yyets.v1.ResourceClass.ALLEntryR\x03ALL\x12\x0e\n" +
	"\x02JP\x18\x02 \x01(\tR\x02JP\x12\x0e\n" +
	"\x02US\x18\x03 \x01(\tR\x02US\x12\x0e\n" +
	"\x02UK\x18\x04 \x01(\tR\x02UK\x12\x0e\n" +
	"\x02KR\x18\x05 \x01(\tR\x02KR\x1a6\n" +
	"\bALLEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12TopResourceRequest\"\xa3\x02\n" +
	"\x10TopResourceReply\x12,\n" +
	"\x03ALL\x18\x01 \x03(\v2\x1a.api.yyets.v1.ResourceItemR\x03ALL\x12*\n" +
	"\x02US\x18\x02 \x03(\v2\x1a.api.yyets.v1.ResourceItemR\x02US\x12*\n" +
	"\x02JP\x18\x03 \x03(\v2\x1a.api.yyets.v1.ResourceItemR\x02JP\x12*\n" +
	"\x02KR\x18\x04 \x03(\v2\x1a.api.yyets.v1.ResourceItemR\x02KR\x12*\n" +
	"\x02UK\x18\x05 \x03(\v2\x1a.api.yyets.v1.ResourceItemR\x02UK\x121\n" +
	"\x05class\x18\x06 \x01(\v2\x1b.api.yyets.v1.ResourceClassR\x05class\"\x17\n" +
	"\x15CreateResourceRequest\"\x15\n" +
	"\x13CreateResourceReply\"\x17\n" +
	"\x15UpdateResourceRequest\"\x15\n" +
	"\x13UpdateResourceReply\"\x17\n" +
	"\x15DeleteResourceRequest\"\x15\n" +
	"\x13DeleteResourceReply\"$\n" +
	"\x12GetResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xca\x01\n" +
	"\x10GetResourceReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06cnname\x18\x02 \x01(\tR\x06cnname\x12\x16\n" +
	"\x06enname\x18\x03 \x01(\tR\x06enname\x12\x1c\n" +
	"\taliasname\x18\x04 \x01(\tR\taliasname\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\x12\x14\n" +
	"\x05views\x18\x06 \x01(\x03R\x05views\x12.\n" +
	"\x04data\x18\a \x01(\v2\x1a.api.yyets.v1.ResourceDataR\x04data\"\x15\n" +
	"\x13ListResourceRequest\"\x13\n" +
	"\x11ListResourceReply\"E\n" +
	"\x15SearchResourceRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xc2\x01\n" +
	"\x13SearchResourceReply\x12:\n" +
	"\bresource\x18\x01 \x03(\v2\x1e.api.yyets.v1.ResourceDataInfoR\bresource\x125\n" +
	"\acomment\x18\x02 \x03(\v2\x1b.api.yyets.v1.SearchCommentR\acomment\x128\n" +
	"\bsubtitle\x18\x03 \x03(\v2\x1c.api.yyets.v1.SearchSubtitleR\bsubtitle\"\x85\x02\n" +
	"\rSearchComment\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x1c\n" +
	"\tcommentID\x18\x04 \x01(\tR\tcommentID\x12\x1e\n" +
	"\n" +
	"resourceID\x18\x05 \x01(\x03R\n" +
	"resourceID\x12\"\n" +
	"\fresourceName\x18\x06 \x01(\tR\fresourceName\x12\x16\n" +
	"\x06origin\x18\a \x01(\tR\x06origin\x12\x1c\n" +
	"\thasAvatar\x18\b \x01(\bR\thasAvatar\x12\x12\n" +
	"\x04hash\x18\t \x01(\tR\x04hash\"\x10\n" +
	"\x0eSearchSubtitle2\xaf\x05\n" +
	"\bResource\x12X\n" +
	"\x0eCreateResource\x12#.api.yyets.v1.CreateResourceRequest\x1a!.api.yyets.v1.CreateResourceReply\x12X\n" +
	"\x0eUpdateResource\x12#.api.yyets.v1.UpdateResourceRequest\x1a!.api.yyets.v1.UpdateResourceReply\x12X\n" +
	"\x0eDeleteResource\x12#.api.yyets.v1.DeleteResourceRequest\x1a!.api.yyets.v1.DeleteResourceReply\x12f\n" +
	"\vGetResource\x12 .api.yyets.v1.GetResourceRequest\x1a\x1e.api.yyets.v1.GetResourceReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/resource\x12R\n" +
	"\fListResource\x12!.api.yyets.v1.ListResourceRequest\x1a\x1f.api.yyets.v1.ListResourceReply\x12a\n" +
	"\vTopResource\x12 .api.yyets.v1.TopResourceRequest\x1a\x1e.api.yyets.v1.TopResourceReply\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/api/top\x12v\n" +
	"\x0eSearchResource\x12#.api.yyets.v1.SearchResourceRequest\x1a!.api.yyets.v1.SearchResourceReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/resource/searchB-\n" +
	"\fapi.yyets.v1P\x01Z\x1bYYeTsBot-Go/api/yyets/v1;v1b\x06proto3"

var (
	file_yyets_v1_resource_proto_rawDescOnce sync.Once
	file_yyets_v1_resource_proto_rawDescData []byte
)

func file_yyets_v1_resource_proto_rawDescGZIP() []byte {
	file_yyets_v1_resource_proto_rawDescOnce.Do(func() {
		file_yyets_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yyets_v1_resource_proto_rawDesc), len(file_yyets_v1_resource_proto_rawDesc)))
	})
	return file_yyets_v1_resource_proto_rawDescData
}

var file_yyets_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_yyets_v1_resource_proto_goTypes = []any{
	(*ResourceDataInfo)(nil),      // 0: api.yyets.v1.ResourceDataInfo
	(*ResourceFile)(nil),          // 1: api.yyets.v1.ResourceFile
	(*ResourceSeasonItem)(nil),    // 2: api.yyets.v1.ResourceSeasonItem
	(*ResourceSeasonList)(nil),    // 3: api.yyets.v1.ResourceSeasonList
	(*ResourceSeason)(nil),        // 4: api.yyets.v1.ResourceSeason
	(*ResourceData)(nil),          // 5: api.yyets.v1.ResourceData
	(*ResourceItem)(nil),          // 6: api.yyets.v1.ResourceItem
	(*ResourceClass)(nil),         // 7: api.yyets.v1.ResourceClass
	(*TopResourceRequest)(nil),    // 8: api.yyets.v1.TopResourceRequest
	(*TopResourceReply)(nil),      // 9: api.yyets.v1.TopResourceReply
	(*CreateResourceRequest)(nil), // 10: api.yyets.v1.CreateResourceRequest
	(*CreateResourceReply)(nil),   // 11: api.yyets.v1.CreateResourceReply
	(*UpdateResourceRequest)(nil), // 12: api.yyets.v1.UpdateResourceRequest
	(*UpdateResourceReply)(nil),   // 13: api.yyets.v1.UpdateResourceReply
	(*DeleteResourceRequest)(nil), // 14: api.yyets.v1.DeleteResourceRequest
	(*DeleteResourceReply)(nil),   // 15: api.yyets.v1.DeleteResourceReply
	(*GetResourceRequest)(nil),    // 16: api.yyets.v1.GetResourceRequest
	(*GetResourceReply)(nil),      // 17: api.yyets.v1.GetResourceReply
	(*ListResourceRequest)(nil),   // 18: api.yyets.v1.ListResourceRequest
	(*ListResourceReply)(nil),     // 19: api.yyets.v1.ListResourceReply
	(*SearchResourceRequest)(nil), // 20: api.yyets.v1.SearchResourceRequest
	(*SearchResourceReply)(nil),   // 21: api.yyets.v1.SearchResourceReply
	(*SearchComment)(nil),         // 22: api.yyets.v1.SearchComment
	(*SearchSubtitle)(nil),        // 23: api.yyets.v1.SearchSubtitle
	nil,                           // 24: api.yyets.v1.ResourceSeason.ItemsEntry
	nil,                           // 25: api.yyets.v1.ResourceClass.ALLEntry
}
var file_yyets_v1_resource_proto_depIdxs = []int32{
	1,  // 0: api.yyets.v1.ResourceSeasonItem.files:type_name -> api.yyets.v1.ResourceFile
	2,  // 1: api.yyets.v1.ResourceSeasonList.items:type_name -> api.yyets.v1.ResourceSeasonItem
	24, // 2: api.yyets.v1.ResourceSeason.items:type_name -> api.yyets.v1.ResourceSeason.ItemsEntry
	0,  // 3: api.yyets.v1.ResourceData.info:type_name -> api.yyets.v1.ResourceDataInfo
	4,  // 4: api.yyets.v1.ResourceData.list:type_name -> api.yyets.v1.ResourceSeason
	5,  // 5: api.yyets.v1.ResourceItem.data:type_name -> api.yyets.v1.ResourceData
	25, // 6: api.yyets.v1.ResourceClass.ALL:type_name -> api.yyets.v1.ResourceClass.ALLEntry
	6,  // 7: api.yyets.v1.TopResourceReply.ALL:type_name -> api.yyets.v1.ResourceItem
	6,  // 8: api.yyets.v1.TopResourceReply.US:type_name -> api.yyets.v1.ResourceItem
	6,  // 9: api.yyets.v1.TopResourceReply.JP:type_name -> api.yyets.v1.ResourceItem
	6,  // 10: api.yyets.v1.TopResourceReply.KR:type_name -> api.yyets.v1.ResourceItem
	6,  // 11: api.yyets.v1.TopResourceReply.UK:type_name -> api.yyets.v1.ResourceItem
	7,  // 12: api.yyets.v1.TopResourceReply.class:type_name -> api.yyets.v1.ResourceClass
	5,  // 13: api.yyets.v1.GetResourceReply.data:type_name -> api.yyets.v1.ResourceData
	0,  // 14: api.yyets.v1.SearchResourceReply.resource:type_name -> api.yyets.v1.ResourceDataInfo
	22, // 15: api.yyets.v1.SearchResourceReply.comment:type_name -> api.yyets.v1.SearchComment
	23, // 16: api.yyets.v1.SearchResourceReply.subtitle:type_name -> api.yyets.v1.SearchSubtitle
	3,  // 17: api.yyets.v1.ResourceSeason.ItemsEntry.value:type_name -> api.yyets.v1.ResourceSeasonList
	10, // 18: api.yyets.v1.Resource.CreateResource:input_type -> api.yyets.v1.CreateResourceRequest
	12, // 19: api.yyets.v1.Resource.UpdateResource:input_type -> api.yyets.v1.UpdateResourceRequest
	14, // 20: api.yyets.v1.Resource.DeleteResource:input_type -> api.yyets.v1.DeleteResourceRequest
	16, // 21: api.yyets.v1.Resource.GetResource:input_type -> api.yyets.v1.GetResourceRequest
	18, // 22: api.yyets.v1.Resource.ListResource:input_type -> api.yyets.v1.ListResourceRequest
	8,  // 23: api.yyets.v1.Resource.TopResource:input_type -> api.yyets.v1.TopResourceRequest
	20, // 24: api.yyets.v1.Resource.SearchResource:input_type -> api.yyets.v1.SearchResourceRequest
	11, // 25: api.yyets.v1.Resource.CreateResource:output_type -> api.yyets.v1.CreateResourceReply
	13, // 26: api.yyets.v1.Resource.UpdateResource:output_type -> api.yyets.v1.UpdateResourceReply
	15, // 27: api.yyets.v1.Resource.DeleteResource:output_type -> api.yyets.v1.DeleteResourceReply
	17, // 28: api.yyets.v1.Resource.GetResource:output_type -> api.yyets.v1.GetResourceReply
	19, // 29: api.yyets.v1.Resource.ListResource:output_type -> api.yyets.v1.ListResourceReply
	9,  // 30: api.yyets.v1.Resource.TopResource:output_type -> api.yyets.v1.TopResourceReply
	21, // 31: api.yyets.v1.Resource.SearchResource:output_type -> api.yyets.v1.SearchResourceReply
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_yyets_v1_resource_proto_init() }
func file_yyets_v1_resource_proto_init() {
	if File_yyets_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yyets_v1_resource_proto_rawDesc), len(file_yyets_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yyets_v1_resource_proto_goTypes,
		DependencyIndexes: file_yyets_v1_resource_proto_depIdxs,
		MessageInfos:      file_yyets_v1_resource_proto_msgTypes,
	}.Build()
	File_yyets_v1_resource_proto = out.File
	file_yyets_v1_resource_proto_goTypes = nil
	file_yyets_v1_resource_proto_depIdxs = nil
}
