server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mongo
    db_name: zimuzu
    # source: mongodb://117.72.37.235:27017
    # source: mongodb://172.25.1.234:27017/zimuzu
    source: mongodb://192.168.1.4:27017/zimuzu
  redis:
    addr: 172.25.1.234:6379
    # addr: 117.72.37.235:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
