name: Build and Push Docker Image to Organization Registry

on:
  push:
    branches: [ "main" ] # Or your main development branch
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  GITHUB_ORGANIZATION: kiki2077
  IMAGE_NAME: yyets-go
  DOCKERFILE_PATH: ./Dockerfile # Adjust if your Dockerfile is in a different location
  BUILD_CONTEXT: . # Adjust if your build context is different

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          latest: true
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.BUILD_CONTEXT }}